theme: minima
plugins:
  - jekyll-feed

title: José L. Seoane
# author: José L. Seoan
# description: >-
#  Blog personal sobre experiencias y reflexiones filosóficas.
email: jlseovaz@gmail.com
# github_username: jlseoane

header_pages:
  - index.md
  - sobre-mi.md

